dist: trusty # needs Ubuntu Trusty
# Note: if you switch to sudo: false, you'll need to launch Chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
language: node_js
node_js:
  - 12
  - 11
  - 10

matrix:
  fast_finish: true
  allow_failures:
    - node_js: 10
  env:
    NODE_ENV: test

branches:
  only:
    - master
    - next
    - develop

install: npm install

script:
  - npm run lint
  - npm run build

before_deploy:
  - npm i -g semantic-release
  - npm i -g @semantic-release/commit-analyzer @semantic-release/release-notes-generator @semantic-release/changelog @semantic-release/npm @semantic-release/git @semantic-release/github

deploy:
  provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    branch: next
