version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:12.9.0
    steps:
      - checkout
      - run:
          name: Setup
          command: npm install
      - run:
          name: Lint and Format
          command: npm run lint
  semantic_release:
    docker:
      - image: circleci/node:12.9.0
    steps:
      - checkout
      - run:
          name: Setup
          command: npm install
      - run:
          name: run 'semantic-release'
          command: npx semantic-release

workflows:
  version: 2
  lint_and_release:
    jobs:
      - lint
      - semantic_release:
          requires:
            - lint
          filters:
            branches:
              only: develop
